### Get all prices
GET http://localhost:3000/api/treatment_prices

### Create price
# @name createPrice
POST http://localhost:3000/api/treatment_prices
Content-Type: application/json

{
    "vigDate": "04-12-2024",
    "cost": 123.5,
    "treatment": 2
}

### ID
@id = {{createPrice.response.body.data.id}}

### Get one price
GET http://localhost:3000/api/treatment_prices/{{id}}

### Update 