### Get all the users
GET http://localhost:3000/api/users

### Get all the users
GET http://localhost:3000/api/users
Content-Type: application/json

{
    "specialtyToSearch": 2
}   

### Create an user
# @name createUser
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "dni": "44848809",
    "firstName": "Kimey",
    "lastName": "Jeandrevin",
    "email": "jeandrevink@gmail.com",
    "password": "contrasenia",
    "age":21,
    "cod_user":1
 }   

### ID
@id = {{createUser.response.body.data.id}}

### Get one user
GET http://localhost:3000/api/users/{{id}}

### Update an user
PUT http://localhost:3000/api/users/{{id}}
Content-Type: application/json

{
    "firstName": "Ricarda",
    "email": "ricarda@gmail.com"
}

### Delete an user
DELETE http://localhost:3000/api/users/{{id}}

### Create another user
# @name createUser2
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "dni": "44848810",
    "firstName": "Ernesto",
    "lastName": "Rodriguez",
    "email": "ERodriguez@gmail.com",
    "password": "123456",
    "age":30,
    "cod_user": 2
}

### Login check
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "dni": "44848809",
    "password": "contrasenia"
}