### Get all the treatments
GET http://localhost:3000/api/treatments


### Create a treatments
# @name createTreatment
POST http://localhost:3000/api/treatments
Content-Type: application/json

{
    "name": "Radiografia",
    "description": "toma imágenes de las estructuras internas del cuerpo"
}

### ID
@id = {{createTreatment.response.body.data.id}}

### Get one treatment
GET http://localhost:3000/api/treatments/{{id}}


### Update a treatment
PUT http://localhost:3000/api/treatments/{{id}}
Content-Type: application/json

{
    "name": "Quirofano",
    "description": "Lugar para realizar cirugias"
}

### Delete a tratment
DELETE http://localhost:3000/api/treatments/{{id}}