### Get all the consultings
GET http://localhost:3000/api/consultings


### Create a consulting
# @name createConsulting
POST http://localhost:3000/api/consultings
Content-Type: application/json

{
    "id": "2",
    "street": "Skibidi",
    "street_number": 12345
}

### ID
@id = {{createConsulting.response.body.data.id}} 

### Get one consulting
GET http://localhost:3000/api/consultings/{{id}}

### Update a consulting
PUT http://localhost:3000/api/consultings/{{id}}
Content-Type: application/json

{
    "street": "Sigma",
    "street_number": 54321
}

### Delete a consulting
DELETE http://localhost:3000/api/consultings/{{id}}