### Get all the specialties
GET http://localhost:3000/api/specialties


### POST
# @name createSpecialty
POST http://localhost:3000/api/specialties
Content-Type: application/json

{
    "name": "Cirujano",
    "price": 125.5
}

### ID
@id = {{createSpecialty.response.body.data.id}}

### Get one specialty
GET http://localhost:3000/api/specialties/{{id}}

### Update a specialty
PUT http://localhost:3000/api/specialties/{{id}}
Content-Type: application/json

{
    "name": "Partero",
    "price": 50.78
}

### Delete a specialty
DELETE http://localhost:3000/api/specialties/{{id}}